language: python

python:
  - '2.7'
  - '3.6'

# The Statsmodels line is to resolve a hopefully temporary problem --
# Statsmodels 0.11 dropped support for Python 2.7, but as of 2020-02-23 is
# being installed anyway by PyPI in Python 2.7 environments. If this isn't
# fixed upstream, the best place to address it is in UrbanSim itself, where we
# can make the Statsmodels version conditional on the Python version.

install:
  - pip install statsmodels==0.10.*  # see comment above
  - pip install .  # baus and requirements
  - pip install coverage pycodestyle pytest  # testing tools
  - pip list

script:
  - pycodestyle baus
  - pycodestyle scripts
  - coverage run --source baus --module pytest --verbose

after_success:
  - coverage report
