name: networks

desc: Regional Accessibility Variables

model_type: networks

node_col: tmnode_id

variable_definitions:

  - name: residential_units_45_ff
    dataframe: buildings
    varname: residential_units
    radius: 2700
    apply: np.log1p

  - name: jobs_15_ff
    filters:
    - building_id != -1
    dataframe: jobs
    radius: 900
    apply: np.log1p

  - name: jobs_45_ff
    filters:
    - building_id != -1
    dataframe: jobs
    radius: 2700
    apply: np.log1p

  - aggregation: sum
    dataframe: households
    decay: flat
    name: sum_income_40_ff
    radius: 2700
    varname: income