name: networks

desc: Regional Accessibility Variables

model_type: networks

node_col: tmnode_id

variable_definitions:

  - name: residential_units_45_cong
    dataframe: buildings
    varname: residential_units
    radius: 2700
    apply: np.log1p

  - name: jobs_15_cong
    filters:
    - building_id != -1
    dataframe: jobs
    radius: 900
    apply: np.log1p

  - name: jobs_45_cong
    filters:
    - building_id != -1
    dataframe: jobs
    radius: 2700
    apply: np.log1p

  - aggregation: sum
    dataframe: households
    decay: flat
    name: sum_income_40_cong
    radius: 2700
    varname: income